import { WebsiteSiteDocument } from '../models/website-config.model';

export function buildDefaultSite(school: any): WebsiteSiteDocument {
  const primary = school.branding?.themeColor || '#0f766e';
  return {
    header: {
      displayName: '',
      logoUrl: '',
      showOrganizationName: true,
      sticky: true,
      navItems: [
        { id: 'nav-home', label: 'Home', href: '/', visible: true },
        { id: 'nav-about', label: 'About', href: '/#about', visible: true },
        { id: 'nav-programs', label: 'Academics', href: '/#programs', visible: true },
        { id: 'nav-gallery', label: 'Campus Life', href: '/#gallery', visible: true },
        { id: 'nav-news', label: 'News & Events', href: '/#news', visible: true },
        { id: 'nav-contact', label: 'Contact', href: '/#contact', visible: true },
      ],
      ctaText: 'Portal Login',
      ctaUrl: '/auth/login',
    },
    pages: [{
      id: 'page-home',
      title: 'Home',
      slug: '',
      showInNavigation: true,
      seoTitle: school.name,
      seoDescription: `Welcome to ${school.name}.`,
      sections: [
        {
          id: 'hero', type: 'hero',
          title: 'Inspiring Young Minds for a Brighter Tomorrow',
          subtitle: 'Learn • Grow • Belong',
          body: `${school.name} is a caring learning community where every student is encouraged to discover their strengths, build confidence and prepare for a brighter future.`,
          imageUrl: '', videoUrl: '', icon: 'School',
          buttonText: 'Explore Our School', buttonUrl: '/#programs',
          background: 'default', alignment: 'left', visible: true, cards: [],
        },
        {
          id: 'stats', type: 'stats', title: '', subtitle: '', body: '',
          imageUrl: '', videoUrl: '', icon: 'Trophy', buttonText: '', buttonUrl: '',
          background: 'default', alignment: 'center', visible: true,
          cards: [
            { id: 'stat-students', title: 'Learning Environment', text: '', value: 'Safe', icon: 'ShieldCheck' },
            { id: 'stat-teachers', title: 'Teaching Team', text: '', value: 'Skilled', icon: 'Users' },
            { id: 'stat-learning', title: 'Student Life', text: '', value: 'Active', icon: 'Heart' },
            { id: 'stat-future', title: 'Learning Focus', text: '', value: 'Future', icon: 'Trophy' },
          ],
        },
        {
          id: 'programs', type: 'programs',
          title: 'A Well-Rounded Education for a Brighter Future',
          subtitle: 'Our Academic Programs',
          body: 'A balanced school experience that develops knowledge, creativity, confidence, wellbeing and character.',
          imageUrl: '', videoUrl: '', icon: 'BookOpen', buttonText: '', buttonUrl: '',
          background: 'default', alignment: 'left', visible: true,
          cards: [
            { id: 'program-1', title: 'Academic Excellence', text: 'Strong foundations, clear learning goals and engaging classroom experiences.', icon: 'BookOpen' },
            { id: 'program-2', title: 'Student Support', text: 'A caring environment where every learner is known, supported and encouraged.', icon: 'Heart' },
            { id: 'program-3', title: 'STEM & Innovation', text: 'Curiosity, problem-solving and practical learning for tomorrow’s world.', icon: 'FlaskConical' },
            { id: 'program-4', title: 'Arts & Creativity', text: 'Opportunities for imagination, expression, performance and creative growth.', icon: 'Palette' },
            { id: 'program-5', title: 'Sports & Wellness', text: 'Healthy habits, teamwork, confidence and active student life.', icon: 'Dumbbell' },
            { id: 'program-6', title: 'Character & Leadership', text: 'Strong values, responsibility and leadership skills for life beyond school.', icon: 'Award' },
          ],
        },
        {
          id: 'about', type: 'about',
          title: 'A Nurturing Community Where Every Child Thrives',
          subtitle: `About ${school.name}`,
          body: `${school.name} brings together caring educators, strong values and meaningful learning experiences to help students grow academically, socially and personally.`,
          imageUrl: '', videoUrl: '', icon: 'Building2',
          buttonText: 'Learn More About Us', buttonUrl: '/#contact',
          background: 'muted', alignment: 'left', visible: true,
          cards: [
            { id: 'about-mission', title: 'Our Mission', text: '', icon: 'BookOpen' },
            { id: 'about-vision', title: 'Our Vision', text: '', icon: 'Sparkles' },
            { id: 'about-values', title: 'Core Values', text: '', icon: 'Heart' },
          ],
        },
        {
          id: 'gallery', type: 'gallery', title: 'Explore Life at Our School',
          subtitle: 'Campus Life', body: 'Share the moments, activities and experiences that make your school community special.',
          imageUrl: '', videoUrl: '', icon: 'Camera', buttonText: '', buttonUrl: '',
          background: 'muted', alignment: 'left', visible: false, cards: [],
        },
        {
          id: 'news', type: 'news', title: 'News & Events',
          subtitle: 'Stay Connected', body: 'Keep families and students informed about important school moments and upcoming activities.',
          imageUrl: '', videoUrl: '', icon: 'CalendarDays', buttonText: '', buttonUrl: '',
          background: 'default', alignment: 'left', visible: false, cards: [],
        },
        {
          id: 'testimonials', type: 'testimonials', title: 'What Our Community Says',
          subtitle: 'School Community', body: '',
          imageUrl: '', videoUrl: '', icon: 'Quote', buttonText: '', buttonUrl: '',
          background: 'muted', alignment: 'center', visible: false, cards: [],
        },
        {
          id: 'staff', type: 'staff', title: 'Meet Our Team',
          subtitle: 'Dedicated Educators', body: '',
          imageUrl: '', videoUrl: '', icon: 'Users', buttonText: '', buttonUrl: '',
          background: 'default', alignment: 'center', visible: false, cards: [],
        },
        {
          id: 'partners', type: 'partners', title: 'Our Partners',
          subtitle: 'Connected Community', body: '',
          imageUrl: '', videoUrl: '', icon: 'Building2', buttonText: '', buttonUrl: '',
          background: 'muted', alignment: 'center', visible: false, cards: [],
        },
        {
          id: 'video', type: 'video', title: 'Discover Our School',
          subtitle: 'Watch Our Story', body: '',
          imageUrl: '', videoUrl: '', icon: 'PlayCircle', buttonText: '', buttonUrl: '',
          background: 'default', alignment: 'center', visible: false, cards: [],
        },
        {
          id: 'faq', type: 'faq', title: 'Frequently Asked Questions',
          subtitle: 'Helpful Information', body: '',
          imageUrl: '', videoUrl: '', icon: 'BookOpen', buttonText: '', buttonUrl: '',
          background: 'default', alignment: 'center', visible: false, cards: [],
        },
        {
          id: 'contact', type: 'contact', title: 'Contact Our School',
          subtitle: 'We Would Love to Hear From You',
          body: 'Get in touch with our school team for general enquiries, admissions information or support.',
          imageUrl: '', videoUrl: '', icon: 'Mail', buttonText: '', buttonUrl: '',
          background: 'dark', alignment: 'left', visible: true, cards: [],
        },
      ],
    }],
    footer: {
      description: `Official website of ${school.name}. A learning community focused on knowledge, character, confidence and a brighter future.`,
      address: school.address || '',
      phone: school.phone || '',
      email: school.email || '',
      quickLinks: [
        { id: 'footer-home', label: 'Home', href: '/', visible: true },
        { id: 'footer-about', label: 'About', href: '/#about', visible: true },
        { id: 'footer-academics', label: 'Academics', href: '/#programs', visible: true },
        { id: 'footer-contact', label: 'Contact', href: '/#contact', visible: true },
        { id: 'footer-login', label: 'Portal Login', href: '/auth/login', visible: true },
      ],
      socials: [],
      copyright: `© ${new Date().getFullYear()} ${school.name}. All rights reserved.`,
    },
    theme: {
      primaryColor: primary,
      secondaryColor: '#082f49',
      accentColor: '#f59e0b',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      buttonStyle: 'pill',
      cardStyle: 'soft',
    },
    seo: {
      siteTitle: school.name,
      description: `${school.name} official school website`,
      keywords: 'school, education, students, learning, academics, campus',
      ogImage: school.branding?.logo || '',
    },
    settings: { contactFormEnabled: true, analyticsEnabled: true },
    defaultLanguage: 'en',
    languages: [
      { code: 'en', label: 'English', direction: 'ltr', enabled: true },
      { code: 'so', label: 'Somali', direction: 'ltr', enabled: false },
      { code: 'ar', label: 'العربية', direction: 'rtl', enabled: false },
    ],
    translations: {},
    media: [],
  };
}
