import { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpen, Download, MoreVertical, Pencil, Plus, Search, Trash2, Upload, X } from 'lucide-react';
import api from '../../../lib/axios';
import { useAuth } from '../../../store/auth-context';
import { type InstitutionType, resolveInstitutionType, institutionTypeLabel } from '../../../lib/institution-type';

type Status = 'draft' | 'published' | 'archived';
type Ref = { _id: string; name?: string; title?: string; code?: string; slug?: string; section?: string; facultyId?: string; departmentId?: string };
type Org = { _id: string; name: string; institutionType?: InstitutionType; organizationType?: InstitutionType };
type Teacher = { _id: string; profile?: { firstName?: string; lastName?: string }; teacherId?: string };
type Course = { _id: string; title: { en: string; so?: string; ar?: string }; category: string; level: string; duration: number; fee: number; status: Status; maxStudents: number; enrolledStudents: number; teacher?: Teacher | null; school?: { _id: string; name: string } | null; class?: Ref | null; description?: { en?: string; so?: string; ar?: string } };

const labelFor = institutionTypeLabel;
const teacherName = (t?: Teacher | null) => t ? `${t.profile?.firstName || ''} ${t.profile?.lastName || ''}`.trim() || t.teacherId || 'Teacher' : 'Unassigned';

function CourseModal({ course, org, onClose, onSaved }: { course?: Course; org: Org; onClose: () => void; onSaved: () => void }) {
  const type = resolveInstitutionType(org);
  const [teachers, setTeachers] = useState<Teacher[]>([]);
  const [classes, setClasses] = useState<Ref[]>([]);
  const [categories, setCategories] = useState<Ref[]>([]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ title: course?.title?.en || '', category: course?.category || '', level: course?.level || 'beginner', duration: course?.duration || 8, fee: course?.fee || 0, maxStudents: course?.maxStudents || 50, teacher: course?.teacher?._id || '', classId: course?.class?._id || '', status: course?.status || 'draft' as Status, description: course?.description?.en || '' });

  useEffect(() => { (async () => { try { const [t, c, cat] = await Promise.all([api.get('/teachers', { params: { school: org._id, status: 'active', limit: 200 } }), api.get('/classes', { params: { schoolId: org._id, status: 'active', limit: 300 } }), api.get('/course-categories', { params: { school: org._id } })]); setTeachers(t.data.data || []); setClasses(c.data.data || []); setCategories(cat.data.data || []); } catch { setTeachers([]); setClasses([]); setCategories([]); } })(); }, [org._id]);

  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setError(''); try { const payload = { title: { en: form.title, so: course?.title?.so || '', ar: course?.title?.ar || '' }, description: { en: form.description, so: course?.description?.so || '', ar: course?.description?.ar || '' }, category: form.category, level: form.level, duration: Number(form.duration), fee: Number(form.fee), maxStudents: Number(form.maxStudents), teacher: form.teacher || undefined, school: org._id, class: form.classId || undefined, status: form.status }; if (course) await api.patch(`/courses/${course._id}`, payload); else await api.post('/courses', payload); onSaved(); onClose(); } catch (err: any) { setError(err.response?.data?.message || 'Failed to save course'); } finally { setSaving(false); } };

  const placement = type === 'school' ? 'Class / Section' : type === 'training_center' ? 'Batch / Cohort' : 'Class / Cohort';
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose}><div className="w-full max-w-xl max-h-[92vh] overflow-y-auto rounded-2xl bg-[var(--color-surface-primary)] p-5 shadow-2xl" onClick={e => e.stopPropagation()}>
    <div className="mb-4 flex items-start justify-between"><div><h2 className="text-lg font-bold">{course ? 'Edit Course' : 'Add Course'}</h2><p className="text-xs text-[var(--color-text-tertiary)]">{labelFor(type)} curriculum</p></div><button onClick={onClose}><X className="h-5 w-5" /></button></div>
    {error && <div className="mb-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-600">{error}</div>}
    <form onSubmit={submit} className="space-y-3">
      <label className="block text-xs font-semibold">Course / Subject Name *<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm" /></label>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Category *<select required value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm"><option value="">Select category</option>{categories.map(c => <option key={c._id} value={c.slug || c.name}>{c.name}</option>)}</select></label><label className="text-xs font-semibold">Level<select value={form.level} onChange={e => setForm({ ...form, level: e.target.value })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label></div>
      <label className="block text-xs font-semibold">{placement}<select value={form.classId} onChange={e => setForm({ ...form, classId: e.target.value })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm"><option value="">No class/cohort</option>{classes.map(c => <option key={c._id} value={c._id}>{c.title || c.name}{c.section ? ` — ${c.section}` : ''}</option>)}</select></label>
      <label className="block text-xs font-semibold">Teacher / Instructor<select value={form.teacher} onChange={e => setForm({ ...form, teacher: e.target.value })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm"><option value="">Unassigned</option>{teachers.map(t => <option key={t._id} value={t._id}>{teacherName(t)}</option>)}</select></label>
      <label className="block text-xs font-semibold">Description<textarea rows={3} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm" /></label>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">Duration<input type="number" min="1" value={form.duration} onChange={e => setForm({ ...form, duration: Number(e.target.value) })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm" /></label><label className="text-xs font-semibold">Fee<input type="number" min="0" value={form.fee} onChange={e => setForm({ ...form, fee: Number(e.target.value) })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm" /></label><label className="text-xs font-semibold">Capacity<input type="number" min="1" value={form.maxStudents} onChange={e => setForm({ ...form, maxStudents: Number(e.target.value) })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm" /></label></div>
      {course && <label className="block text-xs font-semibold">Status<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value as Status })} className="mt-1 w-full rounded-xl border border-[var(--color-border-default)] bg-transparent px-3 py-2 text-sm"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>}
      <div className="flex gap-2 pt-2"><button type="button" onClick={onClose} className="flex-1 rounded-xl border px-4 py-2.5 text-sm">Cancel</button><button disabled={saving} className="flex-1 rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving...' : course ? 'Update Course' : 'Create Course'}</button></div>
    </form>
  </div></div>;
}

export default function CoursesManage() {
  const { user } = useAuth();
  const organizationId = user?.organizationId || (user as any)?.schoolId || '';
  const [org, setOrg] = useState<Org | null>(null);
  const [courses, setCourses] = useState<Course[]>([]);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const [modal, setModal] = useState<Course | 'new' | null>(null);
  const [selected, setSelected] = useState<string[]>([]);
  const type = resolveInstitutionType(org);

  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); try { const [o, c] = await Promise.all([api.get(`/schools/${organizationId}`), api.get('/courses/admin', { params: { school: organizationId, limit: 300 } })]); const raw = o.data.data || o.data; setOrg(raw); setCourses(c.data.data || []); } catch (err: any) { setError(err.response?.data?.message || 'Unable to load courses'); setCourses([]); } finally { setLoading(false); } }, [organizationId]);
  useEffect(() => { load(); }, [load]);

  const filtered = useMemo(() => courses.filter(c => { const q = search.toLowerCase().trim(); return (!q || c.title?.en?.toLowerCase().includes(q) || c.category?.toLowerCase().includes(q) || teacherName(c.teacher).toLowerCase().includes(q)) && (status === 'all' || c.status === status); }), [courses, search, status]);
  const allSelected = filtered.length > 0 && filtered.every(c => selected.includes(c._id));

  const remove = async (id: string) => { if (!window.confirm('Delete this course?')) return; try { await api.delete(`/courses/${id}`); await load(); } catch (err: any) { setError(err.response?.data?.message || 'Failed to delete course'); } };
  const bulkDelete = async () => { if (!selected.length || !window.confirm(`Delete ${selected.length} selected course(s)?`)) return; try { await Promise.all(selected.map(id => api.delete(`/courses/${id}`))); setSelected([]); await load(); } catch (err: any) { setError(err.response?.data?.message || 'Bulk delete failed'); } };
  const exportCourses = async () => { try { const res = await api.get('/courses/export', { params: { school: organizationId }, responseType: 'blob' }); const url = URL.createObjectURL(res.data); const a = document.createElement('a'); a.href = url; a.download = 'courses.xlsx'; a.click(); URL.revokeObjectURL(url); } catch (err: any) { setError(err.response?.data?.message || 'Export failed'); } };
  const importCourses = async (file: File) => { const fd = new FormData(); fd.append('file', file); try { await api.post('/courses/import', fd, { headers: { 'Content-Type': 'multipart/form-data' } }); await load(); } catch (err: any) { setError(err.response?.data?.message || 'Import failed'); } };

  return <div className="space-y-4 p-4 sm:p-6">
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><h1 className="truncate text-xl font-bold">Manage Courses</h1><p className="text-sm text-[var(--color-text-secondary)]">{courses.length} courses · {labelFor(type)} curriculum</p></div><div className="relative shrink-0"><button aria-label="Course actions" onClick={() => setMenuOpen(v => !v)} className="rounded-xl border border-[var(--color-border-default)] p-2.5 hover:bg-[var(--color-surface-tertiary)]"><MoreVertical className="h-5 w-5" /></button>{menuOpen && <div className="absolute right-0 top-11 z-30 w-56 rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-1.5 shadow-xl"><button onClick={() => { setModal('new'); setMenuOpen(false); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-[var(--color-surface-tertiary)]"><Plus className="h-4 w-4" /> Add Course</button><button onClick={() => { exportCourses(); setMenuOpen(false); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-[var(--color-surface-tertiary)]"><Download className="h-4 w-4" /> Export Courses</button><label className="flex cursor-pointer items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-[var(--color-surface-tertiary)]"><Upload className="h-4 w-4" /> Import Courses<input type="file" accept=".csv,.xlsx" className="hidden" onChange={e => { const f = e.target.files?.[0]; if (f) importCourses(f); e.currentTarget.value = ''; }} /></label>{selected.length > 0 && <button onClick={() => { bulkDelete(); setMenuOpen(false); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4" /> Delete Selected ({selected.length})</button>}</div>}</div></div>
    <div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--color-text-tertiary)]" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search courses, categories, teachers..." className="w-full rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] py-2.5 pl-9 pr-3 text-sm" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] px-3 py-2.5 text-sm"><option value="all">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div>
    {error && <div className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600">{error}</div>}
    <label className="flex items-center gap-2 text-xs text-[var(--color-text-tertiary)]"><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : filtered.map(c => c._id))} /> Select all visible</label>
    {loading ? <div className="rounded-2xl border p-8 text-center text-sm text-[var(--color-text-tertiary)]">Loading courses...</div> : filtered.length === 0 ? <div className="rounded-2xl border p-10 text-center"><BookOpen className="mx-auto mb-2 h-8 w-8 text-[var(--color-text-tertiary)]" /><p className="font-medium">No courses found</p><p className="mt-1 text-sm text-[var(--color-text-tertiary)]">Add a course from the three-dot menu.</p></div> : <div className="grid grid-cols-1 gap-3 lg:grid-cols-2 xl:grid-cols-3">{filtered.map(c => <article key={c._id} className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-4 shadow-sm"><div className="flex items-start gap-3"><input type="checkbox" checked={selected.includes(c._id)} onChange={() => setSelected(s => s.includes(c._id) ? s.filter(x => x !== c._id) : [...s, c._id])} className="mt-1" /><div className="min-w-0 flex-1"><h2 className="truncate font-semibold">{c.title?.en || 'Untitled course'}</h2><p className="mt-0.5 text-xs text-[var(--color-text-tertiary)]">{c.category || 'Uncategorized'} · {c.level || '—'}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${c.status === 'published' ? 'bg-green-100 text-green-700' : c.status === 'archived' ? 'bg-gray-100 text-gray-600' : 'bg-amber-100 text-amber-700'}`}>{c.status}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-[var(--color-surface-tertiary)] p-2"><span className="text-[var(--color-text-tertiary)]">Teacher</span><p className="mt-0.5 truncate font-medium">{teacherName(c.teacher)}</p></div><div className="rounded-lg bg-[var(--color-surface-tertiary)] p-2"><span className="text-[var(--color-text-tertiary)]">Students</span><p className="mt-0.5 font-medium">{c.enrolledStudents || 0} / {c.maxStudents || '∞'}</p></div></div><div className="mt-3 rounded-lg border border-[var(--color-border-default)] px-3 py-2 text-xs"><span className="text-[var(--color-text-tertiary)]">{type === 'school' ? 'Class / Section' : type === 'training_center' ? 'Batch / Cohort' : 'Class / Cohort'}</span><p className="mt-0.5 truncate font-medium">{c.class?.title || 'Not assigned'}{c.class?.section ? ` · ${c.class.section}` : ''}</p></div><div className="mt-3 flex gap-2"><button onClick={() => setModal(c)} className="flex-1 rounded-lg border px-3 py-2 text-xs font-medium"><Pencil className="mr-1 inline h-3.5 w-3.5" /> Edit</button><button onClick={() => remove(c._id)} className="rounded-lg border border-red-200 px-3 py-2 text-red-600"><Trash2 className="h-3.5 w-3.5" /></button></div></article>)}</div>}
    {modal && org && <CourseModal course={modal === 'new' ? undefined : modal} org={org} onClose={() => setModal(null)} onSaved={load} />}
  </div>;
}

export { CoursesManage };
