import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Save, ShieldCheck, UserRound } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import api from '../../../lib/axios';

type Action = 'read' | 'create' | 'edit' | 'delete' | 'export' | 'import';
type SidebarItem = { key: string; label: string; section: string; module: string | null };
type StaffUser = { email: string; phone?: string; title?: string; profile?: { firstName?: string; lastName?: string } | null };
type Permission = { module: string; page?: string; actions: Action[] };
type EmployeeProfile = { employeeId: string; dateOfBirth?: string | null; identityNumber?: string; qualification?: string; specialization?: string; joiningDate?: string | null; employmentType: string; employmentStatus: string; notes?: string; address?: Record<string,string>; emergencyContact?: Record<string,string> };

const actionLabels: Record<Action, string> = { read: 'View', create: 'Create', edit: 'Edit', delete: 'Delete', export: 'Export', import: 'Import' };
const actions: Action[] = ['read', 'create', 'edit', 'delete', 'export', 'import'];
const inputClass = 'w-full rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] px-3 py-2.5 text-sm';
const emptyProfile: EmployeeProfile = { employeeId: '', dateOfBirth: '', identityNumber: '', qualification: '', specialization: '', joiningDate: '', employmentType: 'full_time', employmentStatus: 'active', notes: '', address: {}, emergencyContact: {} };

export function StaffAccessManage() {
  const navigate = useNavigate();
  const { staffId } = useParams<{ staffId: string }>();
  const [items, setItems] = useState<SidebarItem[]>([]); const [staff, setStaff] = useState<StaffUser | null>(null); const [selected, setSelected] = useState<string[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]); const [profile, setProfile] = useState<EmployeeProfile>(emptyProfile);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');

  useEffect(() => { if (!staffId) return; (async () => { try { const [sidebarResponse, userResponse, profileResponse] = await Promise.all([api.get('/users/sidebar/catalog'), api.get(`/users/${staffId}`), api.get(`/users/${staffId}/employee-profile`)]); const user = userResponse.data.data || null; setItems(sidebarResponse.data.data || []); setStaff(user); setSelected(user?.sidebarAccess || []); setPermissions(user?.permissions || []); setProfile({ ...emptyProfile, ...(profileResponse.data.data?.employeeProfile || {}) }); } catch (err: any) { setError(err.response?.data?.message || 'Failed to load Staff profile'); } finally { setLoading(false); } })(); }, [staffId]);
  const grouped = useMemo(() => items.reduce<Record<string, SidebarItem[]>>((groups, item) => { (groups[item.section] ||= []).push(item); return groups; }, {}), [items]);
  const updateProfile = (field: keyof EmployeeProfile, value: any) => setProfile((current) => ({ ...current, [field]: value }));
  const updateNested = (group: 'address' | 'emergencyContact', field: string, value: string) => setProfile((current) => ({ ...current, [group]: { ...(current[group] || {}), [field]: value } }));
  const togglePage = (key: string) => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]);
  const toggleSection = (sectionItems: SidebarItem[]) => { const keys = sectionItems.map((item) => item.key); const allSelected = keys.every((key) => selected.includes(key)); setSelected((current) => allSelected ? current.filter((key) => !keys.includes(key)) : Array.from(new Set([...current, ...keys]))); };
  const actionsFor = (page: SidebarItem) => permissions.find((permission) => permission.page === page.key || (!permission.page && permission.module === page.module))?.actions || [];
  const toggleAction = (page: SidebarItem, action: Action) => setPermissions((current) => { if (!page.module) return current; const existing = current.find((permission) => permission.page === page.key); const nextActions = existing?.actions.includes(action) ? existing.actions.filter((item) => item !== action) : [...(existing?.actions || []), action]; const remaining = current.filter((permission) => permission.page !== page.key); return nextActions.length ? [...remaining, { module: page.module, page: page.key, actions: nextActions }] : remaining; });
  const save = async () => { if (!staffId || !profile.employeeId.trim()) { setError('Employee ID is required'); return; } setSaving(true); setError(''); setMessage(''); try { const pagePermissions = items.filter((item) => item.module && selected.includes(item.key)).map((item) => ({ module: item.module!, page: item.key, actions: actionsFor(item) })).filter((permission) => permission.actions.length); await Promise.all([api.patch(`/users/${staffId}/employee-profile`, profile), api.patch(`/users/${staffId}/sidebar-access`, { keys: selected }), api.patch(`/users/${staffId}/permissions`, { permissions: pagePermissions })]); setMessage('Employee profile and access saved successfully.'); } catch (err: any) { setError(err.response?.data?.message || 'Failed to save Staff profile'); } finally { setSaving(false); } };
  const name = staff?.profile ? `${staff.profile.firstName || ''} ${staff.profile.lastName || ''}`.trim() : '';

  return <div className="p-6 pt-20 lg:p-10 lg:pt-10"><div className="mx-auto max-w-6xl space-y-6">
    <div className="flex items-start justify-between gap-4"><div><button onClick={() => navigate('/admin/staff')} className="mb-4 inline-flex items-center gap-2 text-sm text-[var(--color-text-tertiary)] hover:text-primary-600"><ArrowLeft className="h-4 w-4" /> Back to Staff</button><div className="flex items-center gap-3"><UserRound className="h-8 w-8 text-primary-600" /><div><h1 className="text-2xl font-bold sm:text-3xl">Employee Profile</h1><p className="mt-1 text-sm text-[var(--color-text-tertiary)]">{name || staff?.email || 'Staff member'} · HR record and access controls.</p></div></div></div><button onClick={save} disabled={saving || loading} className="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'Saving...' : 'Save profile'}</button></div>
    {message && <div className="rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700">{message}</div>}{error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading ? <div className="py-16 text-center text-sm text-[var(--color-text-tertiary)]">Loading employee profile...</div> : <>
      <section className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-5"><h2 className="mb-4 text-sm font-bold uppercase tracking-wider">Employment</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className={inputClass} placeholder="Employee ID *" value={profile.employeeId} onChange={(e) => updateProfile('employeeId', e.target.value)} /><input className={inputClass} type="date" value={profile.dateOfBirth ? String(profile.dateOfBirth).slice(0,10) : ''} onChange={(e) => updateProfile('dateOfBirth', e.target.value)} /><input className={inputClass} placeholder="Qualification" value={profile.qualification || ''} onChange={(e) => updateProfile('qualification', e.target.value)} /><input className={inputClass} placeholder="Specialization" value={profile.specialization || ''} onChange={(e) => updateProfile('specialization', e.target.value)} /><input className={inputClass} type="date" value={profile.joiningDate ? String(profile.joiningDate).slice(0,10) : ''} onChange={(e) => updateProfile('joiningDate', e.target.value)} /><select className={inputClass} value={profile.employmentType} onChange={(e) => updateProfile('employmentType', e.target.value)}><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option><option value="temporary">Temporary</option><option value="intern">Intern</option></select><select className={inputClass} value={profile.employmentStatus} onChange={(e) => updateProfile('employmentStatus', e.target.value)}><option value="hired">Hired</option><option value="active">Active</option><option value="on_leave">On leave</option><option value="suspended">Suspended</option><option value="resigned">Resigned</option><option value="terminated">Terminated</option><option value="archived">Archived</option></select><input className={inputClass} placeholder="Identity / ID number" value={profile.identityNumber || ''} onChange={(e) => updateProfile('identityNumber', e.target.value)} /></div></section>
      <section className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-5"><h2 className="mb-4 text-sm font-bold uppercase tracking-wider">Address & Emergency Contact</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><input className={inputClass} placeholder="Street / address" value={profile.address?.street || ''} onChange={(e) => updateNested('address','street',e.target.value)} /><input className={inputClass} placeholder="City" value={profile.address?.city || ''} onChange={(e) => updateNested('address','city',e.target.value)} /><input className={inputClass} placeholder="State / region" value={profile.address?.state || ''} onChange={(e) => updateNested('address','state',e.target.value)} /><input className={inputClass} placeholder="Country" value={profile.address?.country || ''} onChange={(e) => updateNested('address','country',e.target.value)} /><input className={inputClass} placeholder="Emergency contact name" value={profile.emergencyContact?.name || ''} onChange={(e) => updateNested('emergencyContact','name',e.target.value)} /><input className={inputClass} placeholder="Emergency phone" value={profile.emergencyContact?.phone || ''} onChange={(e) => updateNested('emergencyContact','phone',e.target.value)} /><input className={inputClass} placeholder="Relationship" value={profile.emergencyContact?.relationship || ''} onChange={(e) => updateNested('emergencyContact','relationship',e.target.value)} /></div><textarea className={`${inputClass} mt-3`} rows={3} placeholder="HR notes" value={profile.notes || ''} onChange={(e) => updateProfile('notes', e.target.value)} /></section>
      <section><div className="mb-3 flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-primary-600" /><div><h2 className="text-lg font-bold">Access & Permissions</h2><p className="text-sm text-[var(--color-text-tertiary)]">Choose pages and actions available to this Staff member.</p></div></div>{Object.entries(grouped).map(([section, sectionItems]) => { const allSelected = sectionItems.every((item) => selected.includes(item.key)); return <div key={section} className="mb-6"><div className="mb-3 flex items-center justify-between"><h3 className="text-xs font-bold uppercase tracking-widest text-[var(--color-text-tertiary)]">{section}</h3><button onClick={() => toggleSection(sectionItems)} className="text-xs font-medium text-primary-600 hover:underline">{allSelected ? 'Uncheck all' : 'Check all'}</button></div><div className="grid gap-4 md:grid-cols-2">{sectionItems.map((item) => { const checked = selected.includes(item.key); const pageActions = actionsFor(item); return <div key={item.key} className={`rounded-2xl border p-4 ${checked ? 'border-primary-300 bg-primary-50/50' : 'border-[var(--color-border-default)] bg-[var(--color-surface-primary)]'}`}><label className="flex cursor-pointer items-center gap-3"><input type="checkbox" checked={checked} onChange={() => togglePage(item.key)} className="sr-only" /><span className={`flex h-5 w-5 items-center justify-center rounded border ${checked ? 'border-primary-600 bg-primary-600 text-white' : 'border-slate-300'}`}>{checked && <Check className="h-3.5 w-3.5" />}</span><span className="text-sm font-semibold">{item.label}</span></label>{item.module && <div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-2 border-t border-[var(--color-border-subtle)] pt-3 sm:grid-cols-3">{actions.map((action) => <label key={action} className={`flex items-center gap-2 text-xs ${checked ? 'text-[var(--color-text-secondary)]' : 'text-[var(--color-text-tertiary)]'}`}><input type="checkbox" checked={pageActions.includes(action)} disabled={!checked} onChange={() => toggleAction(item, action)} className="rounded border-[var(--color-border-default)]" />{actionLabels[action]}</label>)}</div>}</div>; })}</div></div>; })}</section>
    </>}
  </div></div>;
}

export default StaffAccessManage;
