import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { MoreVertical, Search, UserPlus, Upload, Download, Trash2, Eye, Pencil, BookOpen, X, Check } from 'lucide-react';
import api from '../../../lib/axios';
import { useAuth } from '../../../store/auth-context';

type InstitutionType = 'school' | 'college' | 'university' | 'training_center';
type TeacherStatus = 'active' | 'inactive' | 'on_leave';
type CoursePermission = 'COURSE_BUILDER' | 'STUDENT_VIEW';

interface Organization { _id: string; name: string; institutionType?: InstitutionType; organizationType?: string; status?: string; }
interface Teacher { _id: string; teacherId: string; profile?: { firstName?: string; lastName?: string; gender?: string }; user?: { email?: string; phone?: string; isActive?: boolean }; qualification?: string; specialization?: string[]; experience?: number; bio?: string; status: TeacherStatus; joiningDate?: string; coursePermission?: CoursePermission; school?: { _id: string; name: string }; }
interface Course { _id: string; title?: { en?: string; so?: string; ar?: string }; status?: string; teacher?: string | { _id?: string }; class?: { _id?: string; title?: string; section?: string }; }

const inputClass = 'w-full rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-primary-500/20';
const emptyForm = { email: '', password: '', firstName: '', lastName: '', gender: 'male', phone: '', qualification: '', specialization: '', experience: 0, bio: '', joiningDate: new Date().toISOString().slice(0, 10) };

function orgType(org?: Organization): InstitutionType {
  if (org?.institutionType) return org.institutionType;
  if (org?.organizationType === 'university') return 'university';
  if (org?.organizationType === 'training_center') return 'training_center';
  return 'school';
}
function typeLabel(type: InstitutionType) { return ({ school: 'School', college: 'College', university: 'University', training_center: 'Training Center' } as const)[type]; }
function teacherName(t: Teacher) { return `${t.profile?.firstName || ''} ${t.profile?.lastName || ''}`.trim() || 'Unnamed Teacher'; }
function courseTeacherId(c: Course) { return typeof c.teacher === 'string' ? c.teacher : c.teacher?._id || ''; }
function dataOf<T>(res: any): T { return (res?.data?.data ?? res?.data ?? []) as T; }

function StatusBadge({ status }: { status: TeacherStatus }) {
  const cls = status === 'active' ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300' : status === 'on_leave' ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300' : 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300';
  return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${cls}`}>{status.replace('_', ' ')}</span>;
}

function Modal({ title, children, onClose, wide = false }: { title: string; children: React.ReactNode; onClose: () => void; wide?: boolean }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-3 backdrop-blur-sm" onMouseDown={onClose}>
    <div className={`w-full ${wide ? 'max-w-3xl' : 'max-w-xl'} max-h-[92vh] overflow-y-auto rounded-2xl bg-[var(--color-surface-primary)] p-5 shadow-2xl`} onMouseDown={e => e.stopPropagation()}>
      <div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-bold text-[var(--color-text-primary)]">{title}</h2><button onClick={onClose} className="rounded-lg p-1.5 hover:bg-[var(--color-surface-tertiary)]"><X size={18} /></button></div>
      {children}
    </div>
  </div>;
}

function TeacherFormModal({ teacher, organizationId, organization, onClose, onSaved }: { teacher?: Teacher; organizationId: string; organization?: Organization; onClose: () => void; onSaved: () => void }) {
  const edit = !!teacher;
  const [form, setForm] = useState(() => teacher ? { ...emptyForm, email: teacher.user?.email || '', firstName: teacher.profile?.firstName || '', lastName: teacher.profile?.lastName || '', gender: teacher.profile?.gender || 'male', phone: teacher.user?.phone || '', qualification: teacher.qualification || '', specialization: (teacher.specialization || []).join(', '), experience: teacher.experience || 0, bio: teacher.bio || '', joiningDate: teacher.joiningDate ? new Date(teacher.joiningDate).toISOString().slice(0, 10) : emptyForm.joiningDate } : emptyForm);
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const set = (key: string, value: string | number) => setForm(p => ({ ...p, [key]: value }));
  const submit = async (e: React.FormEvent) => {
    e.preventDefault(); setSaving(true); setError('');
    try {
      const payload: any = { firstName: form.firstName, lastName: form.lastName, gender: form.gender, school: organizationId, qualification: form.qualification, specialization: form.specialization.split(',').map(s => s.trim()).filter(Boolean), experience: Number(form.experience), bio: form.bio, joiningDate: form.joiningDate };
      if (edit) { payload.email = form.email; payload.phone = form.phone || undefined; if (form.password) payload.password = form.password; await api.patch(`/teachers/${teacher!._id}`, payload); }
      else { payload.email = form.email; payload.password = form.password; payload.phone = form.phone || undefined; await api.post('/teachers', payload); }
      onSaved(); onClose();
    } catch (e: any) { setError(e.response?.data?.message || e.message || 'Failed to save teacher'); } finally { setSaving(false); }
  };
  const label = typeLabel(orgType(organization));
  return <Modal title={edit ? 'Edit Teacher' : 'Add Teacher'} onClose={onClose}>
    {error && <div className="mb-3 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600 dark:bg-red-950/30">{error}</div>}
    <div className="mb-4 rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-secondary)] p-3 text-sm"><span className="font-semibold">Organization:</span> {organization?.name || label} <span className="ml-2 rounded-full bg-primary-100 px-2 py-0.5 text-xs text-primary-700">{label}</span><p className="mt-1 text-xs text-[var(--color-text-tertiary)]">Academic teaching placement is assigned through courses/classes; the teacher is scoped to this organization.</p></div>
    <form onSubmit={submit} className="space-y-3">
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">First Name *<input className={inputClass} value={form.firstName} onChange={e => set('firstName', e.target.value)} required /></label><label className="text-xs font-semibold">Last Name *<input className={inputClass} value={form.lastName} onChange={e => set('lastName', e.target.value)} required /></label></div>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Gender *<select className={inputClass} value={form.gender} onChange={e => set('gender', e.target.value)}><option value="male">Male</option><option value="female">Female</option></select></label><label className="text-xs font-semibold">Joining Date<input className={inputClass} type="date" value={form.joiningDate} onChange={e => set('joiningDate', e.target.value)} /></label></div>
      <div className="rounded-xl border border-[var(--color-border-default)] p-3"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-primary-600">System Account</p><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Email *<input className={inputClass} type="email" value={form.email} onChange={e => set('email', e.target.value)} required /></label><label className="text-xs font-semibold">Phone<input className={inputClass} value={form.phone} onChange={e => set('phone', e.target.value)} /></label></div><label className="mt-3 block text-xs font-semibold">{edit ? 'New Password (optional)' : 'Password *'}<input className={inputClass} type="password" autoComplete="new-password" minLength={8} value={form.password} onChange={e => set('password', e.target.value)} required={!edit} /></label></div>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Qualification<input className={inputClass} value={form.qualification} onChange={e => set('qualification', e.target.value)} placeholder="e.g. Bachelor's / Master's" /></label><label className="text-xs font-semibold">Experience (years)<input className={inputClass} type="number" min={0} value={form.experience} onChange={e => set('experience', Number(e.target.value))} /></label></div>
      <label className="text-xs font-semibold">Specialization (comma separated)<input className={inputClass} value={form.specialization} onChange={e => set('specialization', e.target.value)} placeholder="Tajweed, Fiqh, Mathematics" /></label>
      <label className="text-xs font-semibold">Bio<textarea className={inputClass} rows={3} value={form.bio} onChange={e => set('bio', e.target.value)} /></label>
      <div className="flex gap-2 pt-2"><button type="button" onClick={onClose} className="flex-1 rounded-xl border border-[var(--color-border-default)] px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="flex-1 rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Saving...' : edit ? 'Update Teacher' : 'Create Teacher'}</button></div>
    </form>
  </Modal>;
}

function ViewModal({ teacher, assignedCourses, onClose }: { teacher: Teacher; assignedCourses: Course[]; onClose: () => void }) {
  return <Modal title="Teacher Details" onClose={onClose}>
    <div className="mb-4 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary-100 text-lg font-bold text-primary-700">{teacher.profile?.firstName?.[0]}{teacher.profile?.lastName?.[0]}</div><h3 className="mt-2 text-lg font-bold">{teacherName(teacher)}</h3><p className="text-xs text-[var(--color-text-tertiary)]">{teacher.teacherId}</p></div>
    <div className="grid grid-cols-1 gap-2 sm:grid-cols-2"><Info label="Email" value={teacher.user?.email || '—'} /><Info label="Phone" value={teacher.user?.phone || '—'} /><Info label="Organization" value={teacher.school?.name || 'Current organization'} /><Info label="Status" value={<StatusBadge status={teacher.status} />} /><Info label="Qualification" value={teacher.qualification || '—'} /><Info label="Experience" value={`${teacher.experience || 0} years`} /><Info label="Specialization" value={teacher.specialization?.join(', ') || '—'} /><Info label="Course Permission" value={teacher.coursePermission === 'STUDENT_VIEW' ? 'Student View' : 'Course Builder'} /></div>
    <div className="mt-4 rounded-xl border border-[var(--color-border-default)] p-3"><div className="mb-2 flex items-center gap-2 font-semibold"><BookOpen size={16} /> Assigned Courses ({assignedCourses.length})</div>{assignedCourses.length ? <div className="space-y-2">{assignedCourses.map(c => <div key={c._id} className="rounded-lg bg-[var(--color-surface-secondary)] px-3 py-2 text-sm"><div className="font-medium">{c.title?.en || 'Untitled course'}</div>{c.class && <div className="text-xs text-[var(--color-text-tertiary)]">{c.class.title || 'Class'}{c.class.section ? ` • ${c.class.section}` : ''}</div>}</div>)}</div> : <p className="text-sm text-[var(--color-text-tertiary)]">No courses assigned.</p>}</div>
    {teacher.bio && <p className="mt-4 text-sm text-[var(--color-text-secondary)]">{teacher.bio}</p>}
  </Modal>;
}
function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-xl border border-[var(--color-border-default)] p-3"><p className="text-xs text-[var(--color-text-tertiary)]">{label}</p><div className="mt-1 text-sm font-medium">{value}</div></div>; }

function CourseAssignmentModal({ teacher, courses, onClose, onSaved }: { teacher: Teacher; courses: Course[]; onClose: () => void; onSaved: () => void }) {
  const assigned = useMemo(() => new Set(courses.filter(c => courseTeacherId(c) === teacher._id).map(c => c._id)), [courses, teacher._id]);
  const [selected, setSelected] = useState<Set<string>>(assigned); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [search, setSearch] = useState('');
  const visible = courses.filter(c => `${c.title?.en || ''} ${c.class?.title || ''}`.toLowerCase().includes(search.toLowerCase()));
  const save = async () => { setSaving(true); setError(''); try { const changes = courses.filter(c => selected.has(c._id) !== assigned.has(c._id)); await Promise.all(changes.map(c => api.patch(`/courses/${c._id}`, { teacher: selected.has(c._id) ? teacher._id : null }))); onSaved(); onClose(); } catch (e: any) { setError(e.response?.data?.message || 'Failed to update course assignments'); } finally { setSaving(false); } };
  const toggle = (id: string) => setSelected(prev => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next; });
  return <Modal title={`Assign Courses — ${teacherName(teacher)}`} onClose={onClose} wide>
    {error && <div className="mb-3 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600 dark:bg-red-950/30">{error}</div>}
    <input className={`${inputClass} mb-3`} value={search} onChange={e => setSearch(e.target.value)} placeholder="Search course or class..." />
    <div className="max-h-[52vh] overflow-y-auto rounded-xl border border-[var(--color-border-default)]">{visible.length ? visible.map(c => { const checked = selected.has(c._id); return <button key={c._id} type="button" onClick={() => toggle(c._id)} className="flex w-full items-center gap-3 border-b border-[var(--color-border-subtle)] px-3 py-3 text-left last:border-0 hover:bg-[var(--color-surface-secondary)]"><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-md border ${checked ? 'border-primary-600 bg-primary-600 text-white' : 'border-[var(--color-border-default)]'}`}>{checked && <Check size={13} />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{c.title?.en || 'Untitled course'}</span><span className="block text-xs text-[var(--color-text-tertiary)]">{c.class?.title || 'No class/cohort'}{c.class?.section ? ` • ${c.class.section}` : ''} • {c.status || 'draft'}</span></span></button>; }) : <p className="p-5 text-center text-sm text-[var(--color-text-tertiary)]">No courses found.</p>}</div>
    <div className="mt-3 flex items-center justify-between text-xs text-[var(--color-text-tertiary)]"><span>{selected.size} selected</span><button type="button" onClick={() => setSelected(new Set(visible.map(c => c._id)))} className="font-semibold text-primary-600">Select visible</button></div>
    <div className="mt-4 flex gap-2"><button onClick={onClose} className="flex-1 rounded-xl border border-[var(--color-border-default)] px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} onClick={save} className="flex-1 rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save Assignments'}</button></div>
  </Modal>;
}

export default function TeachersManage() {
  const { user } = useAuth();
  const organizationId = user?.organizationId || '';
  const [organization, setOrganization] = useState<Organization>(); const [teachers, setTeachers] = useState<Teacher[]>([]); const [courses, setCourses] = useState<Course[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [selected, setSelected] = useState<string[]>([]); const [page, setPage] = useState(1); const pageSize = 20;
  const [menuOpen, setMenuOpen] = useState(false); const [modal, setModal] = useState<'add' | 'view' | 'edit' | 'assign' | null>(null); const [active, setActive] = useState<Teacher>(); const [permSaving, setPermSaving] = useState(false); const fileRef = useRef<HTMLInputElement>(null);

  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); setError(''); try { const [orgRes, teacherRes, courseRes] = await Promise.all([api.get(`/schools/${organizationId}`), api.get('/teachers', { params: { school: organizationId, limit: 100, page: 1 } }), api.get('/courses/admin', { params: { school: organizationId, limit: 200, page: 1 } })]); setOrganization(dataOf<Organization>(orgRes)); setTeachers(dataOf<Teacher[]>(teacherRes) || []); setCourses(dataOf<Course[]>(courseRes) || []); } catch (e: any) { setError(e.response?.data?.message || 'Failed to load teachers'); } finally { setLoading(false); } }, [organizationId]);
  useEffect(() => { load(); }, [load]);

  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return teachers.filter(t => (status === 'all' || t.status === status) && (!q || `${teacherName(t)} ${t.user?.email || ''} ${t.teacherId || ''} ${(t.specialization || []).join(' ')}`.toLowerCase().includes(q))); }, [teachers, search, status]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); useEffect(() => { if (page > pageCount) setPage(pageCount); }, [page, pageCount]); const rows = filtered.slice((page - 1) * pageSize, page * pageSize); const allVisibleSelected = rows.length > 0 && rows.every(t => selected.includes(t._id));
  const assignedCourses = (t: Teacher) => courses.filter(c => courseTeacherId(c) === t._id);

  const removeSelected = async () => { if (!selected.length || !confirm(`Delete ${selected.length} teacher(s)?`)) return; try { await api.delete('/teachers/bulk', { data: { ids: selected } }); setSelected([]); await load(); } catch (e: any) { alert(e.response?.data?.message || 'Failed to delete selected teachers'); } };
  const exportTeachers = async () => { try { const res = await api.get('/teachers/export', { params: { school: organizationId }, responseType: 'blob' }); const url = URL.createObjectURL(res.data); const a = document.createElement('a'); a.href = url; a.download = 'teachers.xlsx'; a.click(); URL.revokeObjectURL(url); } catch (e: any) { alert(e.response?.data?.message || 'Export failed'); } };
  const importTeachers = async (file: File) => { const fd = new FormData(); fd.append('file', file); try { await api.post('/teachers/import', fd, { headers: { 'Content-Type': 'multipart/form-data' } }); await load(); } catch (e: any) { alert(e.response?.data?.message || 'Import failed'); } finally { if (fileRef.current) fileRef.current.value = ''; } };
  const updateStatus = async (t: Teacher, next: TeacherStatus) => { try { await api.patch(`/teachers/${t._id}/status`, { status: next }); await load(); } catch (e: any) { alert(e.response?.data?.message || 'Failed to update status'); } };

  return <div className="space-y-4 p-3 sm:p-5">
    <input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e => e.target.files?.[0] && importTeachers(e.target.files[0])} />
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><h1 className="text-xl font-bold sm:text-2xl">Manage Teachers</h1><p className="text-sm text-[var(--color-text-tertiary)]">{organization?.name || 'Organization'} • {typeLabel(orgType(organization))} • {filtered.length} teacher{filtered.length === 1 ? '' : 's'}</p></div><div className="relative shrink-0"><button onClick={() => setMenuOpen(v => !v)} className="rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-2.5 shadow-sm" aria-label="Teacher actions"><MoreVertical size={20} /></button>{menuOpen && <div className="absolute right-0 z-20 mt-2 w-56 overflow-hidden rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] shadow-xl"><button onClick={() => { setMenuOpen(false); setActive(undefined); setModal('add'); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-sm hover:bg-[var(--color-surface-secondary)]"><UserPlus size={16} /> Add Teacher</button><button onClick={() => { setMenuOpen(false); fileRef.current?.click(); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-sm hover:bg-[var(--color-surface-secondary)]"><Upload size={16} /> Import</button><button onClick={() => { setMenuOpen(false); exportTeachers(); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-sm hover:bg-[var(--color-surface-secondary)]"><Download size={16} /> Export</button>{selected.length > 0 && <button onClick={() => { setMenuOpen(false); removeSelected(); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-950/20"><Trash2 size={16} /> Delete Selected ({selected.length})</button>}</div>}</div></div>
    {error && <div className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600 dark:bg-red-950/30">{error}</div>}
    <div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-text-tertiary)]" /><input className={`${inputClass} pl-9`} value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search teachers, email, ID..." /></div><select className={`${inputClass} sm:w-44`} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="on_leave">On leave</option></select></div>
    <div className="overflow-hidden rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)]"><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead className="bg-[var(--color-surface-secondary)]"><tr><th className="w-10 px-3 py-3"><input type="checkbox" checked={allVisibleSelected} onChange={e => setSelected(e.target.checked ? [...new Set([...selected, ...rows.map(t => t._id)])] : selected.filter(id => !rows.some(t => t._id === id)))} /></th><th className="px-3 py-3 text-left">Teacher</th><th className="px-3 py-3 text-left">ID</th><th className="px-3 py-3 text-left">Qualification</th><th className="px-3 py-3 text-left">Courses</th><th className="px-3 py-3 text-left">Status</th><th className="px-3 py-3 text-right">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-8 text-center">Loading...</td></tr> : rows.length ? rows.map(t => <tr key={t._id} className="border-t border-[var(--color-border-subtle)]"><td className="px-3 py-3"><input type="checkbox" checked={selected.includes(t._id)} onChange={e => setSelected(s => e.target.checked ? [...s, t._id] : s.filter(id => id !== t._id))} /></td><td className="px-3 py-3"><div className="font-semibold">{teacherName(t)}</div><div className="text-xs text-[var(--color-text-tertiary)]">{t.user?.email || '—'}</div></td><td className="px-3 py-3 font-mono text-xs">{t.teacherId}</td><td className="px-3 py-3">{t.qualification || '—'}</td><td className="px-3 py-3">{assignedCourses(t).length}</td><td className="px-3 py-3"><StatusBadge status={t.status} /></td><td className="px-3 py-3"><div className="flex justify-end gap-1"><button title="View" onClick={() => { setActive(t); setModal('view'); }} className="rounded-lg border border-[var(--color-border-default)] p-1.5 hover:bg-[var(--color-surface-secondary)]"><Eye size={16} /></button><button title="Edit" onClick={() => { setActive(t); setModal('edit'); }} className="rounded-lg border border-[var(--color-border-default)] p-1.5 hover:bg-[var(--color-surface-secondary)]"><Pencil size={16} /></button><button title="Assign courses" onClick={() => { setActive(t); setModal('assign'); }} className="rounded-lg border border-[var(--color-border-default)] p-1.5 hover:bg-[var(--color-surface-secondary)]"><BookOpen size={16} /></button><select title="Status" value={t.status} onChange={e => updateStatus(t, e.target.value as TeacherStatus)} className="rounded-lg border border-[var(--color-border-default)] bg-transparent px-1 text-xs"><option value="active">Active</option><option value="on_leave">Leave</option><option value="inactive">Inactive</option></select></div></td></tr>) : <tr><td colSpan={7} className="p-8 text-center text-[var(--color-text-tertiary)]">No teachers found.</td></tr>}</tbody></table></div>
      <div className="md:hidden">{loading ? <div className="p-8 text-center">Loading...</div> : rows.length ? rows.map(t => <div key={t._id} className="border-b border-[var(--color-border-subtle)] p-3 last:border-0"><div className="flex items-start gap-3"><input type="checkbox" checked={selected.includes(t._id)} onChange={e => setSelected(s => e.target.checked ? [...s, t._id] : s.filter(id => id !== t._id))} className="mt-1" /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><div className="truncate font-semibold">{teacherName(t)}</div><StatusBadge status={t.status} /></div><p className="text-xs text-[var(--color-text-tertiary)]">{t.teacherId} • {t.user?.email || '—'}</p><p className="mt-1 text-xs">{t.qualification || 'Qualification not set'} • {assignedCourses(t).length} course(s)</p><div className="mt-2 flex gap-1"><button onClick={() => { setActive(t); setModal('view'); }} className="inline-flex items-center gap-1 rounded-lg border border-[var(--color-border-default)] px-2 py-1.5 text-xs font-medium"><Eye size={14} /> View</button><button onClick={() => { setActive(t); setModal('edit'); }} className="inline-flex items-center gap-1 rounded-lg border border-[var(--color-border-default)] px-2 py-1.5 text-xs font-medium"><Pencil size={14} /> Edit</button><button onClick={() => { setActive(t); setModal('assign'); }} className="inline-flex items-center gap-1 rounded-lg border border-[var(--color-border-default)] px-2 py-1.5 text-xs font-medium"><BookOpen size={14} /> Courses</button></div></div></div></div>) : <div className="p-8 text-center text-[var(--color-text-tertiary)]">No teachers found.</div>}</div></div>
    <div className="flex items-center justify-between text-sm"><span className="text-[var(--color-text-tertiary)]">Page {page} of {pageCount}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(p => p - 1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={page >= pageCount} onClick={() => setPage(p => p + 1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Next</button></div></div>
    {modal === 'add' && <TeacherFormModal organizationId={organizationId} organization={organization} onClose={() => setModal(null)} onSaved={load} />}
    {modal === 'edit' && active && <TeacherFormModal teacher={active} organizationId={organizationId} organization={organization} onClose={() => setModal(null)} onSaved={load} />}
    {modal === 'view' && active && <ViewModal teacher={active} assignedCourses={assignedCourses(active)} onClose={() => setModal(null)} />}
    {modal === 'assign' && active && <CourseAssignmentModal teacher={active} courses={courses} onClose={() => setModal(null)} onSaved={load} />}
    {active && <div className="fixed bottom-3 right-3 z-40 hidden sm:block"><div className="rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-2 shadow-lg"><label className="flex items-center gap-2 text-xs font-semibold">Permission<select value={active.coursePermission || 'COURSE_BUILDER'} disabled={permSaving} onChange={async e => { const next = e.target.value as CoursePermission; try { setPermSaving(true); await api.patch(`/teachers/${active._id}/course-permission`, { coursePermission: next }); await load(); setActive(t => t ? { ...t, coursePermission: next } : t); } catch (err: any) { alert(err.response?.data?.message || 'Failed to update permission'); } finally { setPermSaving(false); } }} className="rounded-lg border px-2 py-1 text-xs"><option value="COURSE_BUILDER">Course Builder</option><option value="STUDENT_VIEW">Student View</option></select></label></div></div>}
  </div>;
}
